# Generated by Django 4.1.2 on 2023-03-11 18:56

import django.core.validators
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=300
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "uuid",
                    models.CharField(
                        default=video.models.generate_id_length,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to=video.models.get_movie_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                            )
                        ],
                        verbose_name="فایل ویدیو",
                    ),
                ),
                (
                    "gif",
                    models.FileField(
                        upload_to=video.models.get_gif_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["gif", "png"]
                            )
                        ],
                        verbose_name="فایل گیف",
                    ),
                ),
                ("cast", models.ManyToManyField(blank=True, to="video.actor")),
            ],
        ),
    ]
