# Generated by Django 4.1.2 on 2023-03-11 19:37

import django.core.validators
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_alter_video_options_video_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="gif",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=video.models.get_gif_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["gif", "png"]
                    )
                ],
                verbose_name="فایل گیف",
            ),
        ),
    ]
