# Generated by Django 4.1.2 on 2023-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_alter_video_gif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
