# Generated by Django 4.2 on 2023-07-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_tag_alter_video_options_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='video.tag'),
        ),
    ]
